// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// import { SolutionTemplateCard } from "../common/models/SolutionTemplateCard";
export const data = "data";
// export const mockCardData1: SolutionTemplateCard = {
//     applicationUniqueId: "DailyConsolidatedTaskList",
//     applicationVersionId:"DailyConsolidatedTaskList",
//     cardTitle: "This is the title of the card that can be up to two lines",
//     cardDescription: "Receive a daily consolidated task list from Microsoft To-Do and Planner. Then manually or automatically add focus time specifically for those items in your calendar.",
//     cardCategory: "Email Management",
//     cardIconUrl: "https://imageassetssa.z5.web.core.windows.net/images/task.png",
//     noOfClicks: 1000,
//     isNew: false,
//     isFeatured: true,
//     cardImageUrl: "https://imageassetssa.z5.web.core.windows.net/images/detailedViewPlaceholder.png",
//     cardVideoUrl: "video.com",
// };

// export const mockCardData2: SolutionTemplateCard = {
//     applicationUniqueId: "Test Automation",
//     applicationVersionId: "Test Automation",
//     cardTitle: "This is the title of the card This is the title of the card This is the title of the card This is the title of the card This is the title of the card This is the title of the card This is the title of the card",
//     cardDescription: "Receive a daily consolidated task list from Microsoft To-Do and Planner. Then manually or automatically add focus time specifically for those items in your calendar.",
//     cardCategory: "Email Management",
//     cardIconUrl: "https://imageassetssa.z5.web.core.windows.net/images/task.png",
//     noOfClicks: 1000,
//     isNew: true,
//     isFeatured: true,
//     cardImageUrl: "https://imageassetssa.z5.web.core.windows.net/images/detailedViewPlaceholder.png",
//     cardVideoUrl: ""
// };

// export const mockItems: SolutionTemplateCard[] = [{
//     applicationUniqueId: "DailyConsolidatedTaskList",
//     applicationVersionId:"DailyConsolidatedTaskList",
//     cardTitle: "This is the title of the card that can be up to two lines",
//     cardDescription: "Receive a daily consolidated task list from Microsoft To-Do and Planner. Then manually or automatically add focus time specifically for those items in your calendar.",
//     cardCategory: "Email Management",
//     cardIconUrl: "https://imageassetssa.z5.web.core.windows.net/images/task.png",
//     noOfClicks: 1000,
//     isNew: false,
//     isFeatured: true,
//     cardImageUrl: "https://imageassetssa.z5.web.core.windows.net/images/detailedViewPlaceholder.png",
//     cardVideoUrl: "video.com",
// },
// {
//     applicationUniqueId: "DailyConsolidatedTaskList",
//     applicationVersionId:"DailyConsolidatedTaskList",
//     cardTitle: "This is the title of the card that can be up to two lines",
//     cardDescription: "Receive a daily consolidated task list from Microsoft To-Do and Planner. Then manually or automatically add focus time specifically for those items in your calendar.",
//     cardCategory: "Email Management",
//     cardIconUrl: "https://imageassetssa.z5.web.core.windows.net/images/task.png",
//     noOfClicks: 1000,
//     isNew: false,
//     isFeatured: true,
//     cardImageUrl: "https://imageassetssa.z5.web.core.windows.net/images/detailedViewPlaceholder.png",
//     cardVideoUrl: "video.com",
// },
// {
//     applicationUniqueId: "DailyConsolidatedTaskList",
//     applicationVersionId:"DailyConsolidatedTaskList",
//     cardTitle: "This is the title of the card that can be up to two lines",
//     cardDescription: "Receive a daily consolidated task list from Microsoft To-Do and Planner. Then manually or automatically add focus time specifically for those items in your calendar.",
//     cardCategory: "Email Management",
//     cardIconUrl: "https://imageassetssa.z5.web.core.windows.net/images/task.png",
//     noOfClicks: 1000,
//     isNew: false,
//     isFeatured: true,
//     cardImageUrl: "https://imageassetssa.z5.web.core.windows.net/images/detailedViewPlaceholder.png",
//     cardVideoUrl: "video.com",
// },
// {
//     applicationUniqueId: "DailyConsolidatedTaskList",
//     applicationVersionId:"DailyConsolidatedTaskList",
//     cardTitle: "This is the title of the card that can be up to two lines",
//     cardDescription: "Receive a daily consolidated task list from Microsoft To-Do and Planner. Then manually or automatically add focus time specifically for those items in your calendar.",
//     cardCategory: "Email Management",
//     cardIconUrl: "https://imageassetssa.z5.web.core.windows.net/images/task.png",
//     noOfClicks: 1000,
//     isNew: false,
//     isFeatured: true,
//     cardImageUrl: "https://imageassetssa.z5.web.core.windows.net/images/detailedViewPlaceholder.png",
//     cardVideoUrl: "video.com",
// },
// {
//     applicationUniqueId: "DailyConsolidatedTaskList",
//     applicationVersionId:"DailyConsolidatedTaskList",
//     cardTitle: "This is the title of the card that can be up to two lines",
//     cardDescription: "Receive a daily consolidated task list from Microsoft To-Do and Planner. Then manually or automatically add focus time specifically for those items in your calendar.",
//     cardCategory: "Email Management",
//     cardIconUrl: "https://imageassetssa.z5.web.core.windows.net/images/task.png",
//     noOfClicks: 1000,
//     isNew: false,
//     isFeatured: true,
//     cardImageUrl: "https://imageassetssa.z5.web.core.windows.net/images/detailedViewPlaceholder.png",
//     cardVideoUrl: "video.com",
// },
// {
//     applicationUniqueId: "DailyConsolidatedTaskList",
//     applicationVersionId:"DailyConsolidatedTaskList",
//     cardTitle: "This is the title of the card that can be up to two lines",
//     cardDescription: "Receive a daily consolidated task list from Microsoft To-Do and Planner. Then manually or automatically add focus time specifically for those items in your calendar.",
//     cardCategory: "Email Management",
//     cardIconUrl: "https://imageassetssa.z5.web.core.windows.net/images/task.png",
//     noOfClicks: 1000,
//     isNew: false,
//     isFeatured: true,
//     cardImageUrl: "https://imageassetssa.z5.web.core.windows.net/images/detailedViewPlaceholder.png",
//     cardVideoUrl: "video.com",
// },
// {
//     applicationUniqueId: "DailyConsolidatedTaskList",
//     applicationVersionId:"DailyConsolidatedTaskList",
//     cardTitle: "This is the title of the card that can be up to two lines",
//     cardDescription: "Receive a daily consolidated task list from Microsoft To-Do and Planner. Then manually or automatically add focus time specifically for those items in your calendar.",
//     cardCategory: "Email Management",
//     cardIconUrl: "https://imageassetssa.z5.web.core.windows.net/images/task.png",
//     noOfClicks: 1000,
//     isNew: false,
//     isFeatured: true,
//     cardImageUrl: "https://imageassetssa.z5.web.core.windows.net/images/detailedViewPlaceholder.png",
//     cardVideoUrl: "video.com",
// },
// {
//     applicationUniqueId: "DailyConsolidatedTaskList",
//     applicationVersionId:"DailyConsolidatedTaskList",
//     cardTitle: "This is the title of the card that can be up to two lines",
//     cardDescription: "Receive a daily consolidated task list from Microsoft To-Do and Planner. Then manually or automatically add focus time specifically for those items in your calendar.",
//     cardCategory: "Email Management",
//     cardIconUrl: "https://imageassetssa.z5.web.core.windows.net/images/task.png",
//     noOfClicks: 1000,
//     isNew: false,
//     isFeatured: true,
//     cardImageUrl: "https://imageassetssa.z5.web.core.windows.net/images/detailedViewPlaceholder.png",
//     cardVideoUrl: "video.com",
// }];

