import { Card } from "../common/models/Card";

export const mockCarouselCards: Card[] = [
    {
        cardUniqueName: "Test Automation",
        cardTitle: "1This is the title of the card This is the title of the card This is the title of the card This is the title of the card This is the title of the card This is the title of the card This is the title of the card",
        cardDescription: "Receive a daily consolidated task list from Microsoft To-Do and Planner. Then manually or automatically add focus time specifically for those items in your calendar.",
        cardLongDescription: "Daily Consolidated Task List will help bring all your tasks into one consolidated list and help you book focus time to complete them. Based on your configuration, you will receive a daily email with a list of your overdue tasks, tasks due today, upcoming tasks, and old tasks without due dates. You can then schedule focus time from the daily email or have it automatically scheduled for you based on your preferences. Each scheduled event will include that day’s consolidated task list in the event details.",
        cardCategory: "Email Management",
        automationUrl: "https://make.preview.powerautomate.com/galleries/public/templates/fea1532598b444dc93bf5b4f11852ebd/?powerautomate-core.enableVariableEditor=true&environment=839eace6-59ab-4243-97ec-a5b8fcc104e4",
        cardIconUrl: "https://imageassetssa.z5.web.core.windows.net/images/task.png",
        cardType: "Automation",
        templateId: "fea1532598b444dc93bf5b4f11852ebd",
        cardDisplayOrder: 1,
        noOfClicks: 1000,
        cardKeywords: "outlook; task; to do; productivity; list; daily;",
        cardSubheader: "This automation will get your tasks from Outlook, To Do, and Planner every day to compile a list of overdue, due today, and upcoming tasks. ",
        cardTimeSavings: 10,
        cardFrequency: "once a week",
        isNew: true,
        isFeatured: true,
        cardTimeSavingsUnit: 'min',
        cardImageUrl: "https://imageassetssa.z5.web.core.windows.net/images/detailedViewPlaceholder.png",
        cardVideoUrl: ""
    },
    {
        cardUniqueName: "Test Automation",
        cardTitle: "2This is the title of the card This is the title of the card This is the title of the card This is the title of the card This is the title of the card This is the title of the card This is the title of the card",
        cardDescription: "Receive a daily consolidated task list from Microsoft To-Do and Planner. Then manually or automatically add focus time specifically for those items in your calendar.",
        cardLongDescription: "Daily Consolidated Task List will help bring all your tasks into one consolidated list and help you book focus time to complete them. Based on your configuration, you will receive a daily email with a list of your overdue tasks, tasks due today, upcoming tasks, and old tasks without due dates. You can then schedule focus time from the daily email or have it automatically scheduled for you based on your preferences. Each scheduled event will include that day’s consolidated task list in the event details.",
        cardCategory: "Email Management",
        automationUrl: "https://make.preview.powerautomate.com/galleries/public/templates/fea1532598b444dc93bf5b4f11852ebd/?powerautomate-core.enableVariableEditor=true&environment=839eace6-59ab-4243-97ec-a5b8fcc104e4",
        cardIconUrl: "https://imageassetssa.z5.web.core.windows.net/images/task.png",
        cardType: "Automation",
        templateId: "fea1532598b444dc93bf5b4f11852ebd",
        cardDisplayOrder: 1,
        noOfClicks: 1000,
        cardKeywords: "outlook; task; to do; productivity; list; daily;",
        cardSubheader: "This automation will get your tasks from Outlook, To Do, and Planner every day to compile a list of overdue, due today, and upcoming tasks. ",
        cardTimeSavings: 10,
        cardFrequency: "once a week",
        isNew: true,
        isFeatured: true,
        cardTimeSavingsUnit: 'min',
        cardImageUrl: "https://imageassetssa.z5.web.core.windows.net/images/detailedViewPlaceholder.png",
        cardVideoUrl: ""
    },
    {
        cardUniqueName: "Test Automation",
        cardTitle: "3This is the title of the card This is the title of the card This is the title of the card This is the title of the card This is the title of the card This is the title of the card This is the title of the card",
        cardDescription: "Receive a daily consolidated task list from Microsoft To-Do and Planner. Then manually or automatically add focus time specifically for those items in your calendar.",
        cardLongDescription: "Daily Consolidated Task List will help bring all your tasks into one consolidated list and help you book focus time to complete them. Based on your configuration, you will receive a daily email with a list of your overdue tasks, tasks due today, upcoming tasks, and old tasks without due dates. You can then schedule focus time from the daily email or have it automatically scheduled for you based on your preferences. Each scheduled event will include that day’s consolidated task list in the event details.",
        cardCategory: "Email Management",
        automationUrl: "https://make.preview.powerautomate.com/galleries/public/templates/fea1532598b444dc93bf5b4f11852ebd/?powerautomate-core.enableVariableEditor=true&environment=839eace6-59ab-4243-97ec-a5b8fcc104e4",
        cardIconUrl: "https://imageassetssa.z5.web.core.windows.net/images/task.png",
        cardType: "Automation",
        templateId: "fea1532598b444dc93bf5b4f11852ebd",
        cardDisplayOrder: 1,
        noOfClicks: 1000,
        cardKeywords: "outlook; task; to do; productivity; list; daily;",
        cardSubheader: "This automation will get your tasks from Outlook, To Do, and Planner every day to compile a list of overdue, due today, and upcoming tasks. ",
        cardTimeSavings: 10,
        cardFrequency: "once a week",
        isNew: true,
        isFeatured: true,
        cardTimeSavingsUnit: 'min',
        cardImageUrl: "https://imageassetssa.z5.web.core.windows.net/images/detailedViewPlaceholder.png",
        cardVideoUrl: ""
    },
    {
        cardUniqueName: "Test Automation",
        cardTitle: "4This is the title of the card This is the title of the card This is the title of the card This is the title of the card This is the title of the card This is the title of the card This is the title of the card",
        cardDescription: "Receive a daily consolidated task list from Microsoft To-Do and Planner. Then manually or automatically add focus time specifically for those items in your calendar.",
        cardLongDescription: "Daily Consolidated Task List will help bring all your tasks into one consolidated list and help you book focus time to complete them. Based on your configuration, you will receive a daily email with a list of your overdue tasks, tasks due today, upcoming tasks, and old tasks without due dates. You can then schedule focus time from the daily email or have it automatically scheduled for you based on your preferences. Each scheduled event will include that day’s consolidated task list in the event details.",
        cardCategory: "Email Management",
        automationUrl: "https://make.preview.powerautomate.com/galleries/public/templates/fea1532598b444dc93bf5b4f11852ebd/?powerautomate-core.enableVariableEditor=true&environment=839eace6-59ab-4243-97ec-a5b8fcc104e4",
        cardIconUrl: "https://imageassetssa.z5.web.core.windows.net/images/task.png",
        cardType: "Automation",
        templateId: "fea1532598b444dc93bf5b4f11852ebd",
        cardDisplayOrder: 1,
        noOfClicks: 1000,
        cardKeywords: "outlook; task; to do; productivity; list; daily;",
        cardSubheader: "This automation will get your tasks from Outlook, To Do, and Planner every day to compile a list of overdue, due today, and upcoming tasks. ",
        cardTimeSavings: 10,
        cardFrequency: "once a week",
        isNew: true,
        isFeatured: true,
        cardTimeSavingsUnit: 'min',
        cardImageUrl: "https://imageassetssa.z5.web.core.windows.net/images/detailedViewPlaceholder.png",
        cardVideoUrl: ""
    },
    {
        cardUniqueName: "Test Automation",
        cardTitle: "5This is the title of the card This is the title of the card This is the title of the card This is the title of the card This is the title of the card This is the title of the card This is the title of the card",
        cardDescription: "Receive a daily consolidated task list from Microsoft To-Do and Planner. Then manually or automatically add focus time specifically for those items in your calendar.",
        cardLongDescription: "Daily Consolidated Task List will help bring all your tasks into one consolidated list and help you book focus time to complete them. Based on your configuration, you will receive a daily email with a list of your overdue tasks, tasks due today, upcoming tasks, and old tasks without due dates. You can then schedule focus time from the daily email or have it automatically scheduled for you based on your preferences. Each scheduled event will include that day’s consolidated task list in the event details.",
        cardCategory: "Email Management",
        automationUrl: "https://make.preview.powerautomate.com/galleries/public/templates/fea1532598b444dc93bf5b4f11852ebd/?powerautomate-core.enableVariableEditor=true&environment=839eace6-59ab-4243-97ec-a5b8fcc104e4",
        cardIconUrl: "https://imageassetssa.z5.web.core.windows.net/images/task.png",
        cardType: "Automation",
        templateId: "fea1532598b444dc93bf5b4f11852ebd",
        cardDisplayOrder: 1,
        noOfClicks: 1000,
        cardKeywords: "outlook; task; to do; productivity; list; daily;",
        cardSubheader: "This automation will get your tasks from Outlook, To Do, and Planner every day to compile a list of overdue, due today, and upcoming tasks. ",
        cardTimeSavings: 10,
        cardFrequency: "once a week",
        isNew: true,
        isFeatured: true,
        cardTimeSavingsUnit: 'min',
        cardImageUrl: "https://imageassetssa.z5.web.core.windows.net/images/detailedViewPlaceholder.png",
        cardVideoUrl: ""
    },
    {
        cardUniqueName: "Test Automation",
        cardTitle: "6This is the title of the card This is the title of the card This is the title of the card This is the title of the card This is the title of the card This is the title of the card This is the title of the card",
        cardDescription: "Receive a daily consolidated task list from Microsoft To-Do and Planner. Then manually or automatically add focus time specifically for those items in your calendar.",
        cardLongDescription: "Daily Consolidated Task List will help bring all your tasks into one consolidated list and help you book focus time to complete them. Based on your configuration, you will receive a daily email with a list of your overdue tasks, tasks due today, upcoming tasks, and old tasks without due dates. You can then schedule focus time from the daily email or have it automatically scheduled for you based on your preferences. Each scheduled event will include that day’s consolidated task list in the event details.",
        cardCategory: "Email Management",
        automationUrl: "https://make.preview.powerautomate.com/galleries/public/templates/fea1532598b444dc93bf5b4f11852ebd/?powerautomate-core.enableVariableEditor=true&environment=839eace6-59ab-4243-97ec-a5b8fcc104e4",
        cardIconUrl: "https://imageassetssa.z5.web.core.windows.net/images/task.png",
        cardType: "Automation",
        templateId: "fea1532598b444dc93bf5b4f11852ebd",
        cardDisplayOrder: 1,
        noOfClicks: 1000,
        cardKeywords: "outlook; task; to do; productivity; list; daily;",
        cardSubheader: "This automation will get your tasks from Outlook, To Do, and Planner every day to compile a list of overdue, due today, and upcoming tasks. ",
        cardTimeSavings: 10,
        cardFrequency: "once a week",
        isNew: true,
        isFeatured: true,
        cardTimeSavingsUnit: 'min',
        cardImageUrl: "https://imageassetssa.z5.web.core.windows.net/images/detailedViewPlaceholder.png",
        cardVideoUrl: ""
    },
    {
        cardUniqueName: "Test Automation",
        cardTitle: "7This is the title of the card This is the title of the card This is the title of the card This is the title of the card This is the title of the card This is the title of the card This is the title of the card",
        cardDescription: "Receive a daily consolidated task list from Microsoft To-Do and Planner. Then manually or automatically add focus time specifically for those items in your calendar.",
        cardLongDescription: "Daily Consolidated Task List will help bring all your tasks into one consolidated list and help you book focus time to complete them. Based on your configuration, you will receive a daily email with a list of your overdue tasks, tasks due today, upcoming tasks, and old tasks without due dates. You can then schedule focus time from the daily email or have it automatically scheduled for you based on your preferences. Each scheduled event will include that day’s consolidated task list in the event details.",
        cardCategory: "Email Management",
        automationUrl: "https://make.preview.powerautomate.com/galleries/public/templates/fea1532598b444dc93bf5b4f11852ebd/?powerautomate-core.enableVariableEditor=true&environment=839eace6-59ab-4243-97ec-a5b8fcc104e4",
        cardIconUrl: "https://imageassetssa.z5.web.core.windows.net/images/task.png",
        cardType: "Automation",
        templateId: "fea1532598b444dc93bf5b4f11852ebd",
        cardDisplayOrder: 1,
        noOfClicks: 1000,
        cardKeywords: "outlook; task; to do; productivity; list; daily;",
        cardSubheader: "This automation will get your tasks from Outlook, To Do, and Planner every day to compile a list of overdue, due today, and upcoming tasks. ",
        cardTimeSavings: 10,
        cardFrequency: "once a week",
        isNew: true,
        isFeatured: true,
        cardTimeSavingsUnit: 'min',
        cardImageUrl: "https://imageassetssa.z5.web.core.windows.net/images/detailedViewPlaceholder.png",
        cardVideoUrl: ""
    },
    {
        cardUniqueName: "Test Automation",
        cardTitle: "8This is the title of the card This is the title of the card This is the title of the card This is the title of the card This is the title of the card This is the title of the card This is the title of the card",
        cardDescription: "Receive a daily consolidated task list from Microsoft To-Do and Planner. Then manually or automatically add focus time specifically for those items in your calendar.",
        cardLongDescription: "Daily Consolidated Task List will help bring all your tasks into one consolidated list and help you book focus time to complete them. Based on your configuration, you will receive a daily email with a list of your overdue tasks, tasks due today, upcoming tasks, and old tasks without due dates. You can then schedule focus time from the daily email or have it automatically scheduled for you based on your preferences. Each scheduled event will include that day’s consolidated task list in the event details.",
        cardCategory: "Email Management",
        automationUrl: "https://make.preview.powerautomate.com/galleries/public/templates/fea1532598b444dc93bf5b4f11852ebd/?powerautomate-core.enableVariableEditor=true&environment=839eace6-59ab-4243-97ec-a5b8fcc104e4",
        cardIconUrl: "https://imageassetssa.z5.web.core.windows.net/images/task.png",
        cardType: "Automation",
        templateId: "fea1532598b444dc93bf5b4f11852ebd",
        cardDisplayOrder: 1,
        noOfClicks: 1000,
        cardKeywords: "outlook; task; to do; productivity; list; daily;",
        cardSubheader: "This automation will get your tasks from Outlook, To Do, and Planner every day to compile a list of overdue, due today, and upcoming tasks. ",
        cardTimeSavings: 10,
        cardFrequency: "once a week",
        isNew: true,
        isFeatured: true,
        cardTimeSavingsUnit: 'min',
        cardImageUrl: "https://imageassetssa.z5.web.core.windows.net/images/detailedViewPlaceholder.png",
        cardVideoUrl: ""
    }
]